version: "3"

services:
    wd-node-frontend-builder:
        build:
          context: ./frontend
        container_name: wd-node-frontend-builder
        volumes:
          - ./public:/srv/build
    wd-php-backend:
        container_name: wd-php-parser
        restart: unless-stopped
        image: php:7-fpm
        volumes:
            - ./backend:/usr/share/nginx/html
    wd-webserver:
        container_name: wd-nginx
        restart: unless-stopped
        image: nginx
        ports:
            - "5002:80"
        volumes:
            - ./default-nginx.conf:/etc/nginx/conf.d/default.conf
            - ./public:/usr/share/nginx/html
networks:
    default:
        external: false
        name: "wd-network"
